# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch

jobs:
  prod-check:
      if: ${{ github.ref == 'refs/heads/master' }}
      runs-on: ubuntu-latest
      steps:
        - run: echo "Deploying to production server on branch $GITHUB_REF"
